# Generated by Django 4.2.7 on 2023-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='post_image',
            field=models.ImageField(upload_to='stories'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
